server:
  port: 1988
spring:
  application:
    name: aiclown-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clound?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #所有entity别名类所有包
  type-aliases-package: com.hd.entity
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1999.com:1999/eureka,http://eureka2000.com:2000/eureka
