server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1999.com:1999/eureka,http://eureka2000.com:2000/eureka
spring:
  application:
    name: aiclown-customer-server
